replicaCount: 2

serviceAccount:
  create: true
  name: ""

image:
  repository: kumarltd/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}
