apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: kumarltd/myapp:latest
        ports:
        - containerPort: 8080
